name = "FLUE"
version = "0.1.0"
license = "MIT"
author = "Ryan Bignell"
maintainer = "ryan07bignell+github@gmail.com"
copyright = "Copyright 2024, Ryan Bignell & Ben Page"
description = "Calculate and analysis the Gluon Propagator from Landau Gauge Fixed anisotropic lattice QCD"
categories = ["Physics"]
keywords = ["lattice", "lattice QCD", "Gluon", "anisotropic", "FASTSUM"]
homepage = "https://fastsum.gitlab.io/"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false


[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[library]
source-dir="src"

[dependencies]
#stdlib = "*"
#openmp = "*"
stdlib = { path = "../stdlib" }
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
fftpack = { git="https://github.com/fortran-lang/fftpack.git" }
toml-f      = { git = "https://github.com/toml-f/toml-f" }
M_stopwatch        = { git = "https://github.com/urbanjost/M_stopwatch.git", branch= "main"}

#[[executable]]
#name="Flue"
#source-dir="app"
#main="main.f90"

[preprocess]
[preprocess.cpp]
suffixes = ["F90"]
macros=['SETGITHASH=Yes']

# fortitude-lint
[extra.fortitude.check]
line-length = 132
ignore = ["S041", "S051", "M022"]
preview = true
