name = "FLUE"
version = "0.1.0"
license = "MIT"
author = "Ryan Bignell"
maintainer = "ryan07bignell+github@gmail.com"
copyright = "Copyright 2024, Ryan Bignell & Ben Page"
description = "Calculate and analysis the Gluon Propagator from Landau Gauge Fixed anisotropic lattice QCD"
categories = ["Physics"]
keywords = ["lattice", "lattice QCD", "Gluon", "anisotropic", "FASTSUM"]
homepage = "https://fastsum.gitlab.io/"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false


[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[library]
source-dir="src"

[dependencies]
stdlib = "*"

[[executable]]
name="Flue"
source-dir="app"
main="main.f90"

[preprocess]
[preprocess.cpp]
suffixes = ["F90"]
macros=['SETGITHASH=Yes']