
fixNum = 5
fixLabels = [ 'k13700', 'G2L-128', 'G2L-56', 'G2L-36', 'G2L-8']


[fix.G2L-8]
gaugePath='/home/ryan/Documents/2025/conf/Gen2L/8x32/'
gaugeFormat='openqcd'
cfgList='/home/ryan/Documents/2025/conf/Gen2L/G2l_8x32.list'
NT=8
NS=32

[fix.G2L-36]
gaugePath='/home/ryan/Documents/2025/conf/Gen2L/36x32/'
gaugeFormat='openqcd'
cfgList='/home/ryan/Documents/2025/conf/Gen2L/G2l_36x32.list'
NT=36
NS=32

[fix.G2L-56]
gaugePath='/home/ryan/Documents/2025/conf/Gen2L/56x32/'
cfgList='/home/ryan/Documents/2025/conf/Gen2L/G2l_56x32.list'
gaugeFormat='openqcd'
NT=56
NS=32

[fix.k13700]
gaugePath='/home/ryan/Documents/2025/conf/PACS-CS/RCNF2+1/RC32x64_B1900Kud01370000Ks01364000C1715'
cfgList='/home/ryan/Documents/2025/conf/PACS-CS/RCNF2+1/k13700.list'
gaugeFormat='cssmILDG'
NT=64
NS=32

[fix.G2L-128]
gaugePath='/home/ryan/Documents/2025/conf/Gen2L/128x32'
gaugeFormat='openqcd'
cfgList='/home/ryan/Documents/2025/conf/Gen2L/G2l_128x32.list'
NT=128
NS=32